#!/bin/bash
set local

echo Running pre-push git hook script

read -p "Repo push detected, would you like to update the code version? [y/n] " -n 1 -r < /dev/tty
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    cd "$(dirname "$0")"

    cd ../../

    old_version=`cat version.txt`
    python version.py 3
    new_version=`cat version.txt`

    git add --all
    git commit --no-verify -m "git hook pre-push auto update version from $old_version to $new_version"
    git push --no-verify 

    echo "Completed version update from $old_version to $new_version"
    echo "The initial push has been cancelled and replaced with a new push for version $new_version"
    read done

    exit 1 # initial push will not execute
fi
exit 0 # push will execute
